### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ThomWright** [circuitsim/circuit-analysis#1]
- [x] Set up [David](https://david-dm.org/) to monitor dependencies
- [x] Improve docs
  - [x] Add API docs to wiki
- [x] Change repo name to something more suitable?
- [x] Set up entrypoint for NPM package
- [x] Publish to NPM
